apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskflow-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskflow-frontend
  template:
    metadata:
      labels:
        app: taskflow-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/prateek269/taskflow-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5173
